// src/components/SellAnItem/Category/Item.jsx
import PropTypes from 'prop-types';

const CategoryItem = ({ categoryName }) => {
    return (
        <div className="position-relative">
            <div>
                <img src="/bidwars-logo-sm.png" alt="category" className="img-fluid w-100" />
            </div>

            <div className="position-absolute top-0 start-0 bottom-0 end-0 bg-dark opacity-75 rounded"></div>

            <div className="position-absolute top-50 start-50 translate-middle">
                <p className="text-white fw-bold live-auction-text text-capitalize">{ categoryName }</p>
            </div>
        </div>
    );
}

CategoryItem.propTypes = {
    categoryName: PropTypes.string.isRequired,
};

export default CategoryItem;

// src/components/SellAnItem/Category/Item.vue
<script setup>
defineProps(['category']);
</script>

<template>
    <div class="position-relative">
        <div>
            <img src="/imgs/bidwars-logo.png" alt="category image" class="img-fluid w-100">
        </div>
        <div class="position-absolute top-0 start-0 bottom-0 end-0 bg-dark opacity-75 rounded"></div>
        <div class="position-absolute top-50 start-50 translate-middle">
            <p class="text-white fw-bold live-auction-text text-capitalize">{{ category.name }}</p>
        </div>
    </div>
</template>
