// src/components/SellAnItem/ItemSalePeriod/Section.vue
<template>
    <section class="sell-your-item-section" id="input-sale-period">
        <div class="container-fluid p-0">
            <div>
                <label for="sale-period" class="mb-2 fw-bold fs-6">How fast would you like your item to be sold?</label>
                <div class="input-group">
                    <p class="me-2">In</p>
                    <input type="number" class="form-control ps-2 p-0" name="sale_period" id="sale-period" placeholder="X">
                    <p class="ms-2">days time?</p>
                </div>
            </div>
        </div>
    </section>
</template>

// src/components/SellAnItem/ItemSalePeriod/Section.jsx
const ItemSalePeriod = () => {
    return (
        <section className="sell-your-item-section" id="input-sale-period">
            <div className="container-fluid p-0">
                <div>
                    <label htmlFor="sale-period" className="mb-2 fw-bold fs-6">How fast would you like your item to be sold?</label>
                    <div className="input-group">
                        <p className="me-2">In</p>
                        <input type="number" className="form-control ps-2 p-0" name="sale_period" id="sale-period" placeholder="X" />
                        <p className="ms-2">days time?</p>
                    </div>
                </div>
            </div>
        </section>
    )
}

export default ItemSalePeriod;
