// src/components/SellAnItem/ItemCondition/SelectPostCondition.vue
<script setup>
import ConditionOption from "./ConditionOption.vue";
</script>

<template>
    
    <div class="mb-3">
        <div class="form-floating">
            <select class="form-select form-select-md" id="acquisition-post-condition" aria-label="select a condition">
                <option selected disabled value="">select a condition (e.g. looks new)</option>
                <ConditionOption :condition="`post`"></ConditionOption>
            </select>
            <label for="acquisition-post-condition">In what condition would you say the item currently is?</label>
        </div>
    </div>

</template>

// src/components/SellAnItem/ItemCondition/SelectPostCondition.jsx
import ConditionOption from "./ConditionOption.jsx";

const SelectPostCondition = () => {
    return (
        <div className="mb-3">
            <div className="form-floating">
                <select className="form-select form-select-md" id="acquisition-post-condition" aria-label="select a condition">
                    <option selected disabled value="">select a condition (e.g. looks new)</option>
                    <ConditionOption condition="post" />
                </select>
                <label htmlFor="acquisition-post-condition">In what condition would you say the item currently is?</label>
            </div>
        </div>
    )
}

export default SelectPostCondition;
