// src/components/SellAnItem/ImageUpload/Section.jsx
import ImageUploadItem from "./Item.jsx";

const ImageUpload = () => {
    return (
        <section className="sell-your-item-section" id="image-upload">
            <div className="container-fluid p-0">
                <div className="text-start mb-4">
                    <h5>Image of Item 
                        {/* <!-- (<span className="fw-lighter">0</span>/3) --> */}
                    </h5>
                    <p className="m-0 text-secondary"><small>It’s important that your item has an appropraite visual representation. Kindly provide <b className="text-dark">1</b> of the most recent image(s) of your item.</small></p>
                </div>
                <div className="row">
                    <ImageUploadItem tag="one"></ImageUploadItem>
                    {/* <ImageUploadItem tag="two"></ImageUploadItem>
                    <ImageUploadItem tag="three"></ImageUploadItem> */}
                </div>
            </div>
        </section>
    );
}

export default ImageUpload;

// src/components/SellAnItem/ImageUpload/Section.vue
<script setup>
import ImageUploadItem from "./Item.vue";
</script>

<template>

    <section class="sell-your-item-section" id="image-upload">
        <div class="container-fluid p-0">
            <div class="text-start mb-4">
                <h5>Image of Item 
                    <!-- (<span class="fw-lighter">0</span>/3) -->
                </h5>
                <p class="m-0 text-secondary"><small>It’s important that your item has an appropraite visual representation. Kindly provide <b class="text-dark">1</b> of the most recent image(s) of your item.</small></p>
            </div>
            <div class="row">
                <ImageUploadItem :tag="`one`"></ImageUploadItem>
                <!-- <ImageUploadItem :tag="`two`"></ImageUploadItem>
                <ImageUploadItem :tag="`three`"></ImageUploadItem> -->
            </div>
        </div>
      </section>

</template>
